title: Top 100 Tennis Players
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6951525395270437
  brandStrength: 1
  rhythmicContrast: 0.5
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: tennisgods
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.719759012805298
layout_spectrum: 0.2468085
